# Event Names Constants
RUNTIME_STARTED = "runtime.started"
RUNTIME_FINISHED = "runtime.finished"
WORKFLOW_STARTED = "workflow.started"
WORKFLOW_COMPLETED = "workflow.completed"
BROWSER_OPENED = "browser.opened"
BROWSER_CLOSED = "browser.closed"
BROWSER_DOWNLOAD_COMPLETED = "browser.download.completed"
BROWSER_UPLOAD_COMPLETED = "browser.upload.completed"
MEMORY_SAVED = "memory.saved"
MEMORY_LOADED = "memory.loaded"
TOOL_EXECUTED = "tool.executed"
TOOL_FAILED = "tool.failed"
PLUGIN_LOADED = "plugin.loaded"
PLUGIN_UNLOADED = "plugin.unloaded"
VOICE_COMMAND_RECEIVED = "voice.command.received"
PLANNER_CREATED = "planner.created"
AGENT_REPLANNED = "agent.replanned"
